import type { Metadata } from "next";
import { VT323, Press_Start_2P } from 'next/font/google';
import { cn } from "@/utils";
import "./globals.css";

const vt323 = VT323({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-vt323',
});

const pressStart = Press_Start_2P({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-press-start',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="es" className={cn("h-full", "antialiased", vt323.variable, pressStart.variable)}>
      <body className="min-h-dvh flex flex-col">
        <scanlines />
        <main className="container mx-auto mt-16 grow">
          {children}
        </main>
      </body>
    </html>
  );
}
